database:
  host: fill_out
  port: 0000
  database: fill_out
  user: fill_out
  password:
  table: fill_out
startup:
  maintenance: false;
  motd: '&aGeneric MOTD Message'
  chat_color: '7'
  prefix_color: 'f'
economy:
  name: '[Economy]'
  currency: '$'