database:
  host: localhost
  port: 3306
  database: minecraft
  user: root
  password:
  table: player_data
startup:
  maintenance: false;
  motd: '&aHello my Buddas'
  chat_color: '7'
  prefix_color: 'f'
economy:
  name: '[Economy]'
  currency: '$'