name: Additions
version: 0.4.6
author: sdfzgufjkfdsgtzr
main: de.sdfzgufjkfdsgtzr.plugin.Main
api-version: 1.13
commands:
  home:
    description: teleports the player to his home
    usage: /home <home>
  sethome:
    description: sets the player's home
    usage: /sethome <home>
  delhome:
    description: deletes the player's home
    usage: /delhome <home>
  service:
    description: provides access to the server's status
    usage: /service [on/off]
  color:
    description: changes the player's name color & message color in chat
    usage: /color [name] <message>
  balance:
    description: shows the current amount of money
    usage: /balance <player>
  pay:
    description: pay money to another player
    usage: /pay <player> <amount>
  slimecheck:
    description: provides information if the player enters a slime chunk
    usage: /slimecheck
  warp:
    description: teleports the player to the warp point
    usage: /warp <warp>
    setwarp:
      description: sets the warp point
      usage: /setwarp <warp>
    delwarp:
      description: deletes the warp point
      usage: /delwarp <warp>